nelmio_api_doc:
    documentation:
        info:
            title: Operation Overthrow API
            description: API for Operation Overthrow
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
