nelmio_api_doc:
    documentation:
        info:
            title: Operation Overthrow API
            description: API for Operation Overthrow
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    tags:
                        - security
                    summary: get JWT Token
                    requestBody:
                        description: User credentials
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                            example: "user@operation-overthrow.com"
                                        password:
                                            type: string
                                            example: "password"
                    responses:
                        '200':
                            description: JWT Token
                            content: 
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: monSuperToken

                        
    areas:
        path_patterns:
            - ^/api(?!/doc$)
