version: "3.8"

services:
  operation_overthrow_api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: operation_overthrow_api:latest
    container_name: operation_overthrow_api
    restart: always
    volumes:
      - ./:/var/www/api:rw
    tty: true
    ports: 
      - 8000:80
    networks:
      - operation_overthrow_network
    depends_on:
      - operation_overthrow_db
    environment:
      DATABASE_URL: mysql://user:password@operation_overthrow_db:3306/operation_overthrow?serverVersion=8
  operation_overthrow_db:
    image: mysql:8
    container_name: operation_overthrow_db
    restart: always
    volumes:
      - operation_overthrow_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operation_overthrow
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - operation_overthrow_network
  operation_overthrow_pma:
    image: phpmyadmin
    restart: always
    ports:
      - 8037:80
    environment:
      - PMA_HOST=operation_overthrow_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - operation_overthrow_db
    networks:
      - operation_overthrow_network
  operation_overthrow_mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - operation_overthrow_network
  

networks:
  operation_overthrow_network:
volumes:
  operation_overthrow_db: