name: Symfony

on: [push]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    # - name: Generate SSL Key for JWT
    #   run: php bin/console lexik:jwt:generate-keypair
    - name: Create Database
      run: |
        mkdir -p data
        touch data/database.sqlite
    - name: Migrate database 
      env:
        DATABASE_URL: sqlite:///%kernel.project_dir%/var/database_test.db
      run: php bin/console d:m:m --no-interaction --env=test --allow-no-migration
    # - name: Loading fixtures
    #   env:
    #     DATABASE_URL: sqlite:///%kernel.project_dir%/var/database_test.db
    #   run: php bin/console d:f:l --no-interaction --env=test
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DATABASE_URL: sqlite:///%kernel.project_dir%/var/database_test.db
      run: vendor/bin/phpunit
